### ISSUE TITLE
Corre

### ISSUE THREAD

**Issue by haskycrawford** [verdanatech/igz#1]
Current
69. menu01Option=$(whiptail --title "${TITULO}" --backtitle "${BANNER}" --menu "Select a option!" --fb 15 50 6 \

Correct
menu01Option=$(whiptail --title "${TITULO}" --backtitle "${BANNER}" --menu "Select an option!" --fb 15 50 6 \

Current
Licence:
- GPL v3 <http://www.gnu.org/licenses/>

Correct
License:
- GPL v3 <http://www.gnu.org/licenses/>

PS.: The great script.

**Comment by glpibr** [comment]
ok
